FROM python:3.13-slim

WORKDIR /app

COPY deployment/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir --upgrade pip && 
pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "src/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
